### ISSUE TITLE
Where is the zip

### ISSUE THREAD

**Issue by MelleD** [TitanNano/hass-alexa-relay#69]
Hey @TitanNano where can i find the zip :)?
Here is nothing https://github.com/TitanNano/hass-alexa-relay/releases
I would like to try Alexa with WireGuard :)

**Comment by TitanNano** [comment]
I never actually published a release yet. 🫣 I think I can do that later today though. I will let you know when it's available.

**Comment by MelleD** [comment]
Cool thanks 

I just built it myself, do I just have to upload the bootstrap.zip in the hass-alexa-relay folder? Not so familiar with Rust :D

**Comment by TitanNano** [comment]
> Cool thanks
> 
> I just built it myself, do I just have to upload the bootstrap.zip in the hass-alexa-relay folder? Not so familiar with Rust :D

Yes that should be right

**Comment by MelleD** [comment]
SOURCE_PEER_IP Where can i find this?

PRIVATE_KEY from the peer1 or from WireGuard?

**Comment by TitanNano** [comment]
> Maybe you can just explain some things to me, I don't have a lot of experience with HA and secruity yet. HA is currently running with the default settings http://homeassistant.local:8123/ and then VPN via WireGuard.
> 
> How exactly do I have to set SSL for the authorization. Do I need an nginx for this or AdGuard? 

Inside the VPN you don't need SSL / TLS to be set up. That's up to you if you want it. For the `Web Authorization URI` though, Amazon requires a domain that is using SSL / TLS and has a valid TLD. For this, I, personally, use both the AdGuard plugin as a local DNS server and the NGINX plugin for TLS. The certificate will not be verified by the Alexa app and can just be ignored during the authorization flow.

> And what do i need for ENDPOINT env?

Endpoint is just your wireguard endpoint. The public IP and your wireguard port.

> SOURCE_PEER_IP Where can i find this? Do you mean the ip from peer1 address (client.conf) PRIVATE_KEY from the peer1 or from WireGuard?

yes correct

**Comment by MelleD** [comment]
> Inside the VPN you don't need SSL / TLS to be set up. That's up to you if you want it. For the `Web Authorization URI` though, Amazon requires a domain that is using SSL / TLS and has a valid TLD. For this, I, personally, use both the AdGuard plugin as a local DNS server and the NGINX plugin for TLS. The certificate will not be verified by the Alexa app and can just be ignored during the authorization flow.

I need no TLS for my internal network. That's fine.
Do have a picture or settings of you nginx config? For this address then you need also port forwarding in your router or other settings?


> Endpoint is just your wireguard endpoint. The public IP and your wireguard port.

Do you have a static public ip? My public ip is changing a lot...



> From Wireguard. In the `client.conf` there is both a public and a private key.
I have different private key for every peer/Interface and a private key in the wireguard folder.

**Comment by TitanNano** [comment]
> I need no TLS for my internal network. That's fine. Do have a picture or settings of you nginx config? For this address then you need also port forwarding in your router or other settings? Because in my router i cannot change the DNS server :(

Port forwarding should not be done as that would defeat the purpose of this setup. If you can't set a DNS server on your router, you have to set the DNS server on your devices. Wireguard clients usually also allow setting a DNS server that will be used while connected to the VPN.

> Do you have a static public ip? My public ip is changing a lot...

There are many free DynDNS providers. You will then use the DynDNS domain instead of the IP.

> I have different private key for every peer/Interface and a private key in the wireguard folder.

It's the private key of the peer.

**Comment by MelleD** [comment]
@TitanNano thanks yes I understand. Maybe first I should try out Tailscale for my setup, maybe it's easier without DNS and DynDNS providers.
